name:                accelerate-playground
version:             0.1.0.0
github:              "githubuser/accelerate-playground"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/accelerate-playground#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate
- accelerate-blas
- accelerate-io
- accelerate-io-vector
- accelerate-llvm
- accelerate-llvm-ptx
- accelerate-llvm-native
- ad-delcont
- backprop
- bytestring
- generic-lens
- heaps
- massiv
- massiv-io
- random
- mwc-random
- reflection
- rio
- streaming
- strict
- type-natural
- vector
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

build-tools: hpack

library:
  other-modules:
  - Numeric.Linear.Accelerate.Internal
  source-dirs: src

executables:
  mnist:
    main: Main.hs
    source-dirs: app/mnist
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N16
    dependencies:
    - accelerate-playground
    - accelerate-io
    - accelerate-io-vector
    - compact
    - filepath
    - foldl
    - massiv
    - massiv-io
    - mnist-core
    - optparse-applicative
    - resourcet
    - rio
    - streaming
    - streaming-bytestring
    - vector

  accelerate-playground-exe:
    main:                Main.hs
    source-dirs:         app/playground
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N16
    dependencies:
    - accelerate-playground
